name: neural-route-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - jupyter 
  - pip
  - pip:
    - faker
    - geopy
    - ortools
    - fastapi
    - uvicorn
    - python-multipart
    - xgboost
    - streamlit
    - folium
    - streamlit-folium